# Generated by Django 4.0.2 on 2022-03-17 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import publicararte.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Tematica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Arte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=250, verbose_name='Descrição')),
                ('formato', models.CharField(choices=[('JPEG', 'JPEG'), ('JPG', 'JPG'), ('SVG', 'SVG'), ('PNG', 'PNG'), ('BPM', 'BPM'), ('TIFF', 'TIFF'), ('GIF', 'GIF'), ('EPS', 'EPS')], default='Sem detalhes', max_length=4)),
                ('preco', models.FloatField(verbose_name='Preço')),
                ('foto', models.ImageField(height_field='image_width', upload_to=publicararte.models.upload_to, verbose_name='Image', width_field='image_height')),
                ('image_width', models.IntegerField(blank=True, null=True)),
                ('image_height', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('aprovado', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicararte.categoria')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artes', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(to='publicararte.Tags')),
                ('tematica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicararte.tematica', verbose_name='Temática')),
            ],
        ),
    ]
